### ISSUE TITLE
Arduino UNO SD Fail

### ISSUE THREAD

**Issue by josnav** [marcrdavis/ArduinoTITO-PlayerTracking#6]
Hi!!! Testing your code ArduinoTITODeluxe, I got "Failed to read config.txt". If I remove code and let more free memory, then it reads config.txt.
I'm using Arduino Uno R3... 

Can you export that sample to Mega?

Thanks

**Comment by marcrdavis** [comment]
HI - That code was tested and is working with the R3; running it on 3 devices right now; if you are running out of memory then one of two things probably happened - you added code or one or more included libraries are not at the right versions; example - the Ethernet library must be set to version 1.0.4 (page 4 of doc) otherwise there is insufficient memory for the sketch. 

The deluxe sketch has virtually no free ram left; if you are looking for something to play with or you want just the TITO functionality on the MEGA, then please use my other sketch in the main project and then you can use the onlyTITO flag to disable the player tracking stuff.

Marc
